#68
grassrootseconomics/my_sarafu pull request #71
Opened 2022-10-24 11:46 UTC by DHRUVA-N-L-CHOUDHARY

2022-10-24 19:16 UTC, BlazingFV reviewed
could you please share some screen shots for the final version of wallet ? so i can cross check .
thanks

2022-10-24 19:20 UTC, DHRUVA-N-L-CHOUDHARY commented
![image](https://user-images.githubusercontent.com/96297602/197608013-8f5f1221-851c-4f60-90cb-69ed3d8870db.png)
![image](https://user-images.githubusercontent.com/96297602/197608049-79e618a6-d0aa-420a-8e0c-88b955f13b0d.png)

2022-10-24 23:05 UTC, BlazingFV commented
okay looks good enough I'll approve it
the code alsk seems fine

2022-10-24 23:11 UTC, BlazingFV approved these changes
good work everything looks fine and the ui looks like
the figma design

2022-10-25 14:24 UTC, kamikazechaser requested changes

2022-10-25 14:24 UTC, kamikazechaser commented on android/app/build.gradle
> -          enable true
This will break the builds. Revert back to true

2022-10-25 14:24 UTC, kamikazechaser commented on android/build.gradle
> +subprojects
Prefer bracket on the same line

2022-10-25 14:24 UTC, kamikazechaser commented on .github/workflows/analyze-build-debug.yaml
> +      - name: Save state
Remove the next 2 steps. echoing random values on CI is not a good practice especially from a security PoV.

2022-10-25 14:24 UTC, kamikazechaser commented on lib/base_widgets/custom_input_box.dart
> +class _CustomTextfieldState extends State<CustomTextfield> {
@sanjh Kindly review this base widget.

2022-10-25 14:30 UTC, kamikazechaser commented
- Remove empty files
- Move import wallet screen to onboarding folder or its own wallet folder

2022-10-26 15:46 UTC, merged